/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'I311352' at '12/7/16 5:18 PM' with Gradle 3.2.1
 *
 * @author I311352, @date 12/7/16 5:18 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
